### ISSUE TITLE
Options referred to in documentation are nowhere to be found

### ISSUE THREAD

**Issue by dsvensson** [andyp123/blender_io_mesh_bsp#25]
> _Before loading the file, you can tweak some options to change how the BSP will be imported into Blender._

Are these supposed to be visible in the import dialog? Broken with newer blender? Don't see any errors though.

**Comment by andyp123** [comment]
The options exist in the file open/import window. This addon was originally created for Blender 2.8, but since then the file options window has changed a fair bit, and I'm not sure the options are visible by default. If you can't see them, try pressing the 'n' key to toggle the options panel on the right of the file open window.

Hope that helps.
